version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker

  mongodb:
    image: mongo
    ports:
      - 27017:27017

  redis:
    image: redis
    ports:
      - 6379:6379
